[package]
name = "toy_cxx"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx         = "1.0.130"
coreba      = { path = "../idealloc/coreba" }

[build-dependencies]
cxx-build   = "1.0.130"

[lib]
crate-type = ["staticlib"]